bundle_controllers:
    resource: ../../bundles/SymfonyBundle/src/Controller/
    type: annotation

app_controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
